apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: java-app
  type: ClusterIP
