pipeline {
    agent any

    environment {
        DOCKERHUB_REPO = 'nizamra'
        JAVA_APP_IMAGE = 'suseventsdetector'
        COMMIT_HASH = ''
        KUBECONFIG = 'C:\\Users\\HP\\.kube\\config'
    }

    stages {
        stage('Retrieve Commit Hash') {
            steps {
                // Download the commit hash file generated by the build pipeline
                copyArtifacts filter: 'commit-hash.txt', projectName: 'java-app'
                
                script {
                    // Read the commit hash from the file
                    COMMIT_HASH = readFile('commit-hash.txt').trim()
                }
            }
        }

        stage('Deploy to Local Kubernetes with Helm') {
            steps {
                script {
                    // Set Helm release name and chart directory
                    def helmRelease = 'java-mysql-app'
                    def chartDir = 'java-app-helm-chart'

                    // Run Helm upgrade or install with the KUBECONFIG set
                    withEnv(["KUBECONFIG=${KUBECONFIG}"]) {
                        sh 'kubectl cluster-info'
                        sh """                            
                            helm upgrade --install ${helmRelease} ${chartDir} \
                            --set app.image=${DOCKERHUB_REPO}/${JAVA_APP_IMAGE}:${COMMIT_HASH}
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
